# Project-wide Gradle settings.
# تنظیم نسخه جاوا برای جلوگیری از خطای invalid source release
org.gradle.java.version=17

# تنظیمات حافظه برای جلوگیری از خطاهای OutOfMemory در CI
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# تنظیمات پایه اندروید
android.useAndroidX=true
android.enableJetifier=true

# نادیده گرفتن خطای عدم تطابق Compile SDK برای جلوگیری از توقف بیلد
android.suppressUnsupportedCompileSdk=36

# فعال‌سازی ویژگی‌های بهبود عملکرد گِرِیدل
org.gradle.configureondemand=true
org.gradle.caching=true
